theme = "onedark"

[editor]
true-color = true
line-number = "relative"
mouse = false
rulers = [120]
shell = ["zsh", "-c"]
bufferline = "always"

[editor.smart-tab]
enable = false

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
C-s = [":w"]
C-o = [":open ~/.config/helix/config.toml"]

# Show code actions
g = { a = "code_action" }
z = { p = ":config-reload", r = ":reload"}

# Deselect text
esc = ["collapse_selection", "keep_primary_selection"]

# Move line up and down
A-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
